# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #333333;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.input_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_text.setFont(font)
        self.input_text.setStyleSheet("background-color: #444444;\n"
"color: #eeeeee;")
        self.input_text.setObjectName("input_text")
        self.gridLayout.addWidget(self.input_text, 2, 0, 1, 1)
        self.output_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.output_text.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.output_text.setFont(font)
        self.output_text.setStyleSheet("background-color: #444444;\n"
"color: #eeeeee;")
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.gridLayout.addWidget(self.output_text, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("color: #eeeeee;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: #eeeeee;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: #fb5d5d;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
" QPushButton:pressed { \n"
"     background-color: #f95d5d;\n"
" }")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("background-color: #111111;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("background-color: #111111;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("background-color: #111111;")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setStyleSheet("QMenuBar {\n"
"    background-color: #444444;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar:item:selected {\n"
"    background-color: #555555;\n"
"    color: #ffffff;\n"
"}")
        self.menubar.setObjectName("menubar")
        self.mode_menu = QtWidgets.QMenu(self.menubar)
        self.mode_menu.setStyleSheet(" QMenu {\n"
"     background-color: #666666;\n"
"     border: 1px solid black;\n"
" }\n"
"\n"
" QMenu:item {\n"
"     background-color: transparent;\n"
"     color: #ffffff;\n"
" }\n"
"\n"
" QMenu:item:selected { \n"
"     background-color: #777777;\n"
" }")
        self.mode_menu.setObjectName("mode_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setStyleSheet(" QMenu {\n"
"     background-color: #666666;\n"
"     border: 1px solid black;\n"
" }\n"
"\n"
" QMenu:item {\n"
"     background-color: transparent;\n"
"     color: #ffffff;\n"
" }\n"
"\n"
" QMenu:item:selected { \n"
"     background-color: #777777;\n"
" }")
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.code = QtWidgets.QAction(MainWindow)
        self.code.setObjectName("code")
        self.decode = QtWidgets.QAction(MainWindow)
        self.decode.setObjectName("decode")
        self.help = QtWidgets.QAction(MainWindow)
        self.help.setObjectName("help")
        self.mode_menu.addAction(self.code)
        self.mode_menu.addAction(self.decode)
        self.help_menu.addAction(self.help)
        self.menubar.addAction(self.mode_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Поле для ввода текста"))
        self.label_2.setText(_translate("MainWindow", "Поле вывода текста"))
        self.pushButton.setText(_translate("MainWindow", "Кодировать"))
        self.mode_menu.setTitle(_translate("MainWindow", "Режим"))
        self.help_menu.setTitle(_translate("MainWindow", "Помощь"))
        self.code.setText(_translate("MainWindow", "Кодирование"))
        self.decode.setText(_translate("MainWindow", "Декодирование"))
        self.help.setText(_translate("MainWindow", "Помощь"))
